// <auto-generated />
using Bryllup.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bryllup.Migrations
{
    [DbContext(typeof(BryllupDbContext))]
    partial class BryllupDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bryllup.Data.Attendee", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<string>("Comment")
                        .HasMaxLength(4000);

                    b.Property<string>("Name1")
                        .HasMaxLength(100);

                    b.Property<bool>("Name1Attending");

                    b.Property<string>("Name2")
                        .HasMaxLength(100);

                    b.Property<bool>("Name2Attending");

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.HasKey("UserName");

                    b.ToTable("Attendee");
                });
#pragma warning restore 612, 618
        }
    }
}
